# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # Configuração da primeira VM

  #firewall
  #vm pai
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/bionic64"  # Box Ubuntu 18.04 LTS
    vm1.vm.hostname = "vm1"
    vm1.vm.network "forwarded_port", guest: 80, host: 8888
    vm1.vm.provider "virtualbox" do |vb1|
      vb1.memory = "512"
    end
    config.vm.provision "shell", path: "configuracoes.sh"
  end

  # Configuração da segunda VM
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/bionic64"  # Box Ubuntu 18.04 LTS
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.56.10", auto_config: false
    vm2.vm.provider "virtualbox" do |vb2|
      vb2.memory = "512"
    end
    config.vm.provision "shell", path: "route1.sh"
  end

  # Configuração da terceira VM
  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "ubuntu/bionic64"  # Box Ubuntu 18.04 LTS
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", ip: "192.168.56.15"
    vm3.vm.provider "virtualbox" do |vb3|
      vb3.memory = "512"
    end
    config.vm.provision "shell", path: "route2.sh"
  end

end
