# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # Configuração da primeira VM - Servidor (DHCP, DNS e Firewall)
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/focal64" 
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.56.10" 
    vm1.vm.provider "virtualbox" do |vb1|
      vb1.memory = "512"
      vb1.cpus = 1
      vb1.gui = false
      vm1.vm.synced_folder ".", "/vm1"
    end
    vm1.vm.provision "shell", path: "servidor.sh"
  end

  # Configuração da segunda VM - Cliente
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/focal64"  
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", type: "dhcp" 
    vm2.vm.provider "virtualbox" do |vb2|
      vb2.memory = "512"
      vb2.cpus = 1
      vb2.gui = false
      vm2.vm.synced_folder ".", "/vm"    
    end
    vm2.vm.provision "shell", path: "./rotas.sh"
  end

  # Configuração da terceira VM - Cliente
  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "ubuntu/focal64"  
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", type: "dhcp"
    vm3.vm.provider "virtualbox" do |vb3|
      vb3.memory = "512"
      vb3.cpus = 1
      vb3.gui = false
      vm3.vm.synced_folder ".", "/vm"    
    end
    vm3.vm.provision "shell", path: "./rotas.sh"
  end

end