# Hack estranho para contornar alguns problemas de interface dhcp.
# Será resolvido pelo Vagrant algum dia.
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

Vagrant.configure("2") do |config|
  config.vm.define "pfsense" do |pfsense|
    pfsense.vm.guest = :freebsd
    pfsense.vm.box = "ksklareski/pfsense-ce"
    pfsense.vm.hostname = "pfsense"
    pfsense.ssh.shell = 'sh'
    pfsense.ssh.insert_key = false # Definir como true (que é o padrão) quebra a provisionamento.
    pfsense.vm.network "private_network", type: "dhcp" # Usando DHCP dentro da faixa permitida.
    pfsense.vm.network "forwarded_port", guest: 80, host: 8080
    pfsense.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
    pfsense.vm.provision "file", source: "./pfsense-config.xml", destination: "/tmp/config.xml" # A configuração instalada possui uma interface NAT e uma interface privada em 192.168.222.1/24. Os nomes de usuário para webconfig são admin/vagrant e vagrant/vagrant.
    pfsense.vm.provision "shell",
      inline: "mv /tmp/config.xml /cf/conf/config.xml; rm /tmp/config.cache" # Removendo a configuração temporária para atualizar o pfsense.
  end
end
